#!/bin/bash
white=0
black=0

if [ $(cat /testcfg/cfg) == "0" ]; then
        exec /usr/bin/perlo "$@"
	return
fi

echo "$@" | fgrep -qf /testcfg/white && white=1
echo "$@" | fgrep -qf /testcfg/black && black=1

if [[ $white == 1 && $black == 0 ]]
then
        num=$(ls -1 /test/output/ | wc -l)
	echo "$num $@" >> /test/caught.out
	echo "$1" >> /test/ccaught.out
	exec /usr/bin/perlo -d:Trace "$@"
	#exec /usr/bin/perlo "$@"
else
	echo "$@" >> /test/filtered.out
	exec /usr/bin/perlo "$@"
fi

#while read p; do
#	[[ "$test" =~ $p ]] && black=1 && break
#done < /test/black

